### ISSUE TITLE
GitHub Community Profile

### ISSUE THREAD

**Issue by nelsonic** [dwyl/hits-elixir#6]
Each GitHub project now has a "Community Profile" under the "Insights" tab:
https://github.com/dwyl/hits-elixir/community
![image](https://user-images.githubusercontent.com/194400/30258067-1f1b16ea-96ae-11e7-8b70-621f910df6e4.png)

I have no _objection_ to adding these files and think they are a good "first issue" ... 

# Todo / Tasks

+ [x] Add Code of Conduct
+ [x] Add Contributing guide linked to https://github.com/dwyl/contributing
+ [x] Add `LICENSE` file (GPL v.2) see: https://github.com/dwyl/intellectual-property
